security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:        [ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/.*
            provider: fos_userbundle
            form_login:
                provider:      fos_userbundle
                login_path:    fos_user_security_login
                check_path:    fos_user_security_check
                csrf_provider: form.csrf_provider
                remember_me:   true
            logout:
                path: fos_user_security_logout
                target: /
            anonymous: true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/, role: IS_AUTHENTICATED_FULLY }
